# Generated by Django 6.0.4 on 2026-05-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('kaspi', 'Kaspi Pay'), ('card', 'Банковская карта онлайн'), ('cash', 'Наличными курьеру')], default='kaspi', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
