# Generated by Django 6.0.4 on 2026-06-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_products', to='store.color', verbose_name='Цвет оригинала'),
        ),
    ]
