# Generated by Django 6.0.4 on 2026-06-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_original_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Размер'),
        ),
    ]
