# Generated by Django 6.0.5 on 2026-06-16 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderitem_color_name_orderitem_size_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост (см)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (кг)')),
                ('chest', models.PositiveIntegerField(blank=True, null=True, verbose_name='Обхват груди (см)')),
                ('waist', models.PositiveIntegerField(blank=True, null=True, verbose_name='Обхват талии (см)')),
                ('hips', models.PositiveIntegerField(blank=True, null=True, verbose_name='Обхват бедер (см)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Параметры тела',
                'verbose_name_plural': 'Параметры тела',
            },
        ),
    ]
