# Generated by Django 6.0.5 on 2026-06-16 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_bodyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hero', 'Hero-баннер (полноэкранный)'), ('category_pills', 'Кнопки категорий (Pills)'), ('two_column', 'Два блока рядом (Сплит)'), ('banner_cta', 'Широкий баннер с кнопкой'), ('cards', 'Карточки (Сетка)'), ('product_grid', 'Сетка реальных товаров (слайдеры, корзина)'), ('text', 'Текстовый блок')], max_length=20, verbose_name='Тип блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок / Текст')),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='blocks/', verbose_name='Основная картинка / Видео')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка кнопки')),
                ('title_secondary', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (2 колонка)')),
                ('subtitle_secondary', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок (2 колонка)')),
                ('image_secondary', models.ImageField(blank=True, null=True, upload_to='blocks/', verbose_name='Картинка (2 колонка)')),
                ('button_text_secondary', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки (2 колонка)')),
                ('button_link_secondary', models.CharField(blank=True, max_length=255, verbose_name='Ссылка кнопки (2 колонка)')),
            ],
            options={
                'verbose_name': 'Блок главной страницы',
                'verbose_name_plural': 'Блоки главной страницы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок карточки')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок / Подпись')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/items/', verbose_name='Картинка')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Элемент блока',
                'verbose_name_plural': 'Элементы блока',
                'ordering': ['order'],
            },
        ),
    ]
