# Generated by Django 6.0.5 on 2026-06-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_block_blockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
            ],
            options={
                'verbose_name': 'Подписчик рассылки',
                'verbose_name_plural': 'Подписчики рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
