# Generated by Django 6.0.5 on 2026-06-24 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код промокода')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент (%)'), ('fixed', 'Сумма (₸)')], default='percent', max_length=10, verbose_name='Тип скидки')),
                ('discount_value', models.PositiveIntegerField(verbose_name='Размер скидки')),
                ('usage_limit', models.PositiveIntegerField(default=0, verbose_name='Лимит использований (0 - без лимита)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Использовано раз')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действителен до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.promocode', verbose_name='Примененный промокод'),
        ),
    ]
