# Generated by Django 6.0.5 on 2026-06-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_promocode_order_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название рассылки')),
                ('type', models.CharField(default='Email', max_length=50, verbose_name='Тип')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Текст рассылки')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Отправлено')),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name='Открыто')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Переходы')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Заказы')),
                ('status', models.CharField(default='Отправлено', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
                'ordering': ['-created_at'],
            },
        ),
    ]
